name: web_angular
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  ngdart: ^8.0.0-dev.2
  ngcomponents: ^3.0.0-dev.1

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.7
  build_web_compilers: ^3.2.6
